deployment:
  tasks:
    - export DEPLOYPATH=/home/w31m4tv6s92g/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp reviews.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH